### DISCUSSION TITLE
Parsing CSS string adds unwanted &#x3D; entity at the bottom of a base64 font

### DISCUSSION THREAD

**Discussion by vitto** [postcss/postcss#1718] [Q&A] [answered]
Hi, I'm trying to pass a CSS string in postcss plug-in but it sanitize (maybe?) it by adding a `&#x3D;` the the bottom of `src: url("data:font/truetype;charset=utf-8;base64,......&#x3D;=")` CSS declaration.

I've wrote a postcss plugin to integrate my node module inside postcss and webpack, this is the plugin:

```typescript
/* typescript */
import { parse, Plugin } from 'postcss'
import { build } from '@iconsauce/core'

const plugin = (): Plugin => {
  return {
    postcssPlugin: 'postcss-iconsauce',
    async AtRule (rule) {
      if (rule.name === 'iconsauce') {
        rule.replaceWith(parse(await build()))
      }
    },
  }
}

export const postcss = true
plugin.postcss = true
module.exports = plugin
```

Basically I use it with a custom rule `@iconsauce`

So this is the CSS I pass to postcss:

```css
/* css */
@iconsauce;
```
My module will search for icon occurrences in the project to generate an icon font:

```css
:root {
  --iconsauce-font-size: 24px;
}

@font-face {
  font-family: "iconsauce";
  src: url(data:font/truetype;charset=utf-8;base64,AAEAAAALAIAAAwAwR1NVQiCLJXoAAAE4AAAAVE9TLzIzSUCGAAABjAAAAGBjbWFwiwju8gAAAhAAAAHSZ2x5ZtTQhWwAAAP4AAACvGhlYWQblU22AAAA4AAAADZoaGVhADAAIgAAALwAAAAkaG10eADAAAAAAAHsAAAAJGxvY2EDCgO6AAAD5AAAABRtYXhwARgAPQAAARgAAAAgbmFtZcchV/AAAAa0AAACInBvc3S9XDMUAAAI2AAAANoAAQAAABgAAAAAABgAAAAAABcAAQAAAAAAAAAAAAAAAAAAAAkAAQAAAAEAAKyev6tfDzz1AAsAGAAAAADeMAhFAAAAAN4wCEUAAAAAABcAFwAAAAgAAgAAAAAAAAABAAAACQAxAAUAAAAAAAIAAAAKAAoAAAD/AAAAAAAAAAEAAAAKADAAPgACREZMVAAObGF0bgAaAAQAAAAAAAAAAQAAAAQAAAAAAAAAAQAAAAFsaWdhAAgAAAABAAAAAQAEAAQAAAABAAgAAQAGAAAAAQAAAAQAFQGQAAUAAAAPABAAAAADAA8AEAAAAAsAAQAGAAACAAUDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBmRWQAwOoB6ggAGAAAAAIAGgAAAAAAAQAAAAAAAAAAAAAAAAACAAAAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAAAAABQAAAAMAAAAsAAAABAAAAWIAAQAAAAAAXAADAAEAAAAsAAMACgAAAWIABAAwAAAABAAEAAEAAOoI//8AAOoB//8AAAABAAQAAAABAAIAAwAEAAUABgAHAAgAAAEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAHAAAAAAAAAACAAA6gEAAOoBAAAAAQAA6gIAAOoCAAAAAgAA6gMAAOoDAAAAAwAA6gQAAOoEAAAABAAA6gUAAOoFAAAABQAA6gYAAOoGAAAABgAA6gcAAOoHAAAABwAA6ggAAOoIAAAACAAAAAAAAABGAIAAmgC+AOIBHgFIAV4AAwAAAAAAEwAWAAgAGwAwAAA3MBYyNjQmIgYHIxQGIiY0NjM1Ig4BFB4BMj4BNyM3NScrAQcXNzMHFRc7ARUzNTAmDwECAQECAQECAgICAgEBAwEBAwIDAQMCAgEBBgICAQICAQEFAgETAgIBAQENAQICAgICAQMCAwEBAwUDAQIDAQIEAQIFBgIAAAAFAAAAAAAXABUAAwAHAAsAFwAqAAA3MxUjNzMVIyczFSM3NSMVIxUzFTM1MzUHIzUzNSMiBh0BFBY7ATI2PQEjBgICCAICBAICCgIDAwIDBQ4MDAEBAQEOAQECDgcEBAoKCgMDAgMDAgwOAgEBDgEBAQEFAAEAAAAAABMAEwALAAA3JwcnBxcHFzcXNycTAQYGAQYGAQYGAQYSAQYGAQYGAQYGAQYAAAADAAAAAAAWABYADAAQABQAADciDgEUHgEyPgE0LgEHIzUzNSM1MwwDBAMDBAYEAwMEAgICAgIWAwQGBAMDBAYEAw8CAgYAAAADAAAAAAAWABYADAAQABQAADciDgEUHgEyPgE0LgEHIzUzNSM1MwwDBAMDBAYEAwMEAgICAgIWAwQGBAMDBAYEAw8GAgIAAAAEAAAAAAAXABcAEQAXAB0AJgAANy8BBx8BBxQWOwEXBhQWMjcXJzAxNzMXNzAzNzUjFSIGFBYyNjQmFxQCAQQDAgEBBwIBAQIBAg4BAgIEAQQOAQEBAgEBARQCAgQFAwEBAQECAQEDCQICAggBDgECAQECAQAAAAACAAAAAAAXABMAEQAaAAA3LgEiDgEUHgEyNjczFTM1MzUHIiY0NjIWFAYNAQMEAgICAgQDAQQEAhABAQECAQEOAgICAgQCAgICBAQEBAECAQECAQADAAAAAAAXABYAAgAGAAoAADczJxcjNTM1IzUzARYLAQICAgIDExACAgQAAAAAEADGAAEAAAAAAAEACQAAAAEAAAAAAAIABwAJAAEAAAAAAAMACQAQAAEAAAAAAAQACQAZAAEAAAAAAAUACwAiAAEAAAAAAAYACQAtAAEAAAAAAAoAKwA2AAEAAAAAAAsAEwBhAAMAAQQJAAEAEgB0AAMAAQQJAAIADgCGAAMAAQQJAAMAEgCUAAMAAQQJAAQAEgCmAAMAAQQJAAUAFgC4AAMAAQQJAAYAEgDOAAMAAQQJAAoAVgDgAAMAAQQJAAsAJgE2aWNvbnNhdWNlUmVndWxhcmljb25zYXVjZWljb25zYXVjZVZlcnNpb24gMS4waWNvbnNhdWNlR2VuZXJhdGVkIGJ5IHN2ZzJ0dGYgZnJvbSBGb250ZWxsbyBwcm9qZWN0Lmh0dHA6Ly9mb250ZWxsby5jb20AaQBjAG8AbgBzAGEAdQBjAGUAUgBlAGcAdQBsAGEAcgBpAGMAbwBuAHMAYQB1AGMAZQBpAGMAbwBuAHMAYQB1AGMAZQBWAGUAcgBzAGkAbwBuACAAMQAuADAAaQBjAG8AbgBzAGEAdQBjAGUARwBlAG4AZQByAGEAdABlAGQAIABiAHkAIABzAHYAZwAyAHQAdABmACAAZgByAG8AbQAgAEYAbwBuAHQAZQBsAGwAbwAgAHAAcgBvAGoAZQBjAHQALgBoAHQAdABwADoALwAvAGYAbwBuAHQAZQBsAGwAbwAuAGMAbwBtAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAQIBAwEEAQUBBgEHAQgBCQEKABxnbS9maWxsZWQvYWNjZXNzaWJsZS1mb3J3YXJkE2dtL2ZpbGxlZC9hZGQtY2hhcnQPZ20vZmlsbGVkL2Nsb3NlD2dtL2ZpbGxlZC9lcnJvcg5nbS9maWxsZWQvaW5mbx5nbS9maWxsZWQvcmVtb3ZlLXNob3BwaW5nLWNhcnQRZ20vZmlsbGVkL3Zwbi1rZXkRZ20vZmlsbGVkL3dhcm5pbmcAAAAA) format("truetype");

  /* A short version */
  src: url(data:font/truetype;charset=utf-8;base64,AAEAA...AAAAA) format("truetype");
}

[class^="gm/"], [class*=" gm/"] {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  font-family: "iconsauce" !important;
  font-size: var(--iconsauce-font-size);
  font-style: normal;
  text-align: center;
  width: var(--iconsauce-font-size);
}

.gm\/filled\/accessible-forward::before { content: "\ea01"}
.gm\/filled\/add-chart::before { content: "\ea02"}
.gm\/filled\/close::before { content: "\ea03"}
.gm\/filled\/error::before { content: "\ea04"}
.gm\/filled\/info::before { content: "\ea05"}
.gm\/filled\/remove-shopping-cart::before { content: "\ea06"}
.gm\/filled\/vpn-key::before { content: "\ea07"}
.gm\/filled\/warning::before { content: "\ea08"}
```

This is what it outputs:

```css
...

@font-face {
  font-family: "iconsauce";
  /* A short version, note &#x3D; added before = */
  src: url("data:font/truetype;charset=utf-8;base64,AAEAA...AAAAA&#x3D;") format("truetype");
}

...
```

This character is added every time, I've also [tried directly on codepen](https://codepen.io/mobify/pen/DRyBoB) and I confirm it  breaks the font.

What am I missing?
