### DISCUSSION TITLE
can `tokenize.js` support single line comment in module.scss ?

### DISCUSSION THREAD

**Discussion by chaishi** [postcss/postcss#1826] [General]
```css
// a.module.scss
@value mod from 'test.module.scss';
```

```css
// test.module.scss
.mod {
  // hello
  color: yellow;
  font-size: 30px;
}
```

`tokenize.js` can not recognise `// hello` in `test.module.scss`
