### DISCUSSION TITLE
walkRules traverse keyframes within AtRules

### DISCUSSION THREAD

**Discussion by Den-dp** [postcss/postcss#1865] [Q&A] [answered]
Is it expected that `walkRules` will traverse keyframes within AtRules?

Example:

```css
@keyframes foo {
  from { width: 10px; }
  to { width: 100px; }
}
a {
  color: hotpink;
}
```

```js
const plugin = () => ({
  postcssPlugin: "postcss-add-namespace",
  Once(root) {
    root.walkRules((rule) => {
      rule.selectors = rule.selectors.map((selector) => {
        return ':where(app-component) ' + selector;
      });
    });
  }
});

plugin.postcss = true;

export default plugin;
```
results in:
```css
@keyframes foo {
  :where(app-component) from { width: 10px; }
  :where(app-component) to { width: 100px; }
}
:where(app-component) a {
  color: hotpink;
}
```

https://astexplorer.net/#/gist/6d9c942509d8345201f37837275a607a/c1046403587f6bd64b68a806c703453d7da21d2c
