### ISSUE TITLE
How to delete a specific property?

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss#100]
Example:

``` css
.foo {
  padding: 1em;
  float:left;
  display:block;
}
```

When " float≠none", I need to delete "display: block"。I think the API documentation is relatively difficult to understand for me.
