### ISSUE TITLE
Custom props, custom prop sets, semicolons

### ISSUE THREAD

**Issue by pascalduez** [postcss/postcss#1014]
Greetings,

PostCSS version: `6.0.1`.

if you remove a custom property set declaration which is declared after a custom property declaration, that one lose its semicolon.

Here's a demo reproducing the issue:
https://runkit.com/pascalduez/591053890c1a3d001243eb35

```css
/* input */
:root {
  --should-stay: 'test';
  --should-be-removed: {
    content: 'gone';
  };
};
```
```css
/* result */
:root {
  --should-stay: 'test'
};
```
```css
/* expected */
:root {
  --should-stay: 'test';
};
```
