### ISSUE TITLE
How to more easily access units and value?

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss#103]
Now there is such a demand:

input:

``` css
.bar {
  position: center;
  width: 100rem;
  height: 200px;
}
```

If the rule has " position: center" ," width" and " height",
output:

``` css
.bar {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 100rem;
  height: 200px;
  margin-left: 50rem;
  margin-top: 100px;
}
```

Whose margin is equal to the value of "width" or "height" divided by 2, and it ensure the unit is the same. I can only use a regular expression to match it?
