### ISSUE TITLE
Incorrect input for escape sequence

### ISSUE THREAD

**Issue by sebastiandedeyne** [postcss/postcss#1059]
The output of the following is incorrect. I'm using the latest version of PostCSS, this used to work.

Input:

```css
.cell.\-1\/2 {
    width: 50%;
}
```

Output:

```css
.cell.-1\/2 {
    width: 50%;
}
```

But I'm expecting this:

```css
.cell.\-1\/2 {
    width: 50%;
}
```
