### ISSUE TITLE
double sourceMappingURL in output

### ISSUE THREAD

**Issue by gmoulin** [postcss/postcss#106]
Hi,
great job on this tool.

I have a problem with processors and a double sourceMappingURL (original + generated) in the output.

The grunt configuration :

``` javascript
postcss: { //grunt-postcss
    options: {
        map: true,
        processors: [
            require('autoprefixer-core')({browsers: ['last 2 versions', 'ie 8', 'ie 9']}).postcss,
            require('css-mqpacker').postcss,
            require('csswring').postcss
        ]
    },
    // files
}          
```

And the output :

``` css
//rules
/*# sourceMappingURL=global.css.map */@media(min-width:768px){.header__logo{border-bottom-width:0;padding-bottom:20px}.body--scrolled .header__logo{display:block}.mobileNav{display:none}}
/*# sourceMappingURL=global.min.css.map */
```

If I remove "css-mqpacker" from the processor, no problem but I loose the media queries merging.
I tried to put it before autoprefixer, after csswring, same bug.

I have created an issue on css-mqpacker repository too ([#21](https://github.com/hail2u/node-css-mqpacker/issues/21)).
