### ISSUE TITLE
PostCSS now able to get into the picture width and height of it?

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss#107]
For example, when dealing with 2x pictures:

input:

``` css
.foo {
  background-image: -webkit-image-set(
                    url(../img/foo@1x.png) 1x,
                    url(../img/foo@2x.png) 2x);
}
```

output:

``` css
.foo {
  background-image: url(../img/foo@1x.png);
}

@media
  only screen and (-o-min-device-pixel-ratio: 2/1), /* Opera */
  only screen and (min--moz-device-pixel-ratio: 2), /* Firefox 16- */
  only screen and (-moz-min-device-pixel-ratio: 2), /* Firefox */
  only screen and (-webkit-min-device-pixel-ratio: 2), /* WebKit */
  only screen and (min-resolution: 192dpi),
  only screen and (min-resolution: 2dppx)
{
  .foo {
    background-image:url(../img/foo@2x.png);/* Retina */
    background-size: (2x.png-width/2)px (2x.png-height/2)px;
  }
}
```
