### ISSUE TITLE
Can't prevent postcss adding prefixes

### ISSUE THREAD

**Issue by geryit** [postcss/postcss#1079]
My webpack config:
```js
{ test: /\.css$/, use: ['babel-loader', 'raw-loader', 'postcss-loader'] },
```

postcss.config.js:
```js
module.exports = { plugins: [ require('cssnano')({ autoprefixer: false }) ] };
```

src.css:
```css
.box {
  transform: translate3d(0, 0, 0);
  -moz-border-radius: 10px;
  border-radius: 10px;
  display: flex;
}
```

dest.css:
```css
.box{-webkit-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0);
border-radius:10px;
display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex}
```
What am I missing here?
