### ISSUE TITLE
how to implement custom css (token) rules? rules that not part of the spec

### ISSUE THREAD

**Issue by SerkanSipahi** [postcss/postcss#1082]
Is there any description for how to implement there own rules from parsing, transformation to code generation into postcss, maybe as plugin :)
```css
@if {{shouldAttributeName}} { // only curly braces {{.*}}
    .bar {
        font-size: var(--some-box-size-a);
        color: {{shouldAttributeName2}}
    }
}
```
