### ISSUE TITLE
How to compose className from library to rewrite global class?

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [postcss/postcss#1091]
Question guys: I need to rewrite default bootstrap classes, basically adding custom font from my library, which lays in node_modules.

I want something like this:
```css
:global {
  & .form-group {
    & label {
      composes: font-medium from 'ui-components/src/common-styles/font.pcss';

      color: var(--N700);
      margin: 4px 0;
      width: 100%;
    }
  }
}
```

How could I achieve that?

Thanks.
