### ISSUE TITLE
Comments are included in code.

### ISSUE THREAD

**Issue by pxwee5** [postcss/postcss#1293]
```css
.container {
max-width: 1200px;

  /* Acts like clear: both. Prevents previous rows from vertically overflowing into each another. */
  &:before,
  &:after {
    content: '';
    display: flex;
  }
}
```

Produced:
![image](https://user-images.githubusercontent.com/14123790/62755128-d74dc580-bac6-11e9-8956-961b945faa5a.png)

Raised in https://github.com/csstools/postcss-preset-env/issues/144 copied here.
