### ISSUE TITLE
Prevent Cross Site Scripting attacks with PostCSS

### ISSUE THREAD

**Issue by jwerre** [postcss/postcss#1297]
I'm looking for a way to clean user generated CSS on the server side. Is PostCSS able to remove [XSS attacks](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#rule-4---css-escape-and-strictly-validate-before-inserting-untrusted-data-into-html-style-property-values) embedded in CSS? e.g.:

```css
body {
    background-image: url("javascript: malware()");
}
```
