### ISSUE TITLE
Semicolon  and comments questions

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss#131]
``` js
var postcss = require('postcss');

var doubler = postcss(function (css) {
    css.eachDecl(function (decl) {
        decl.parent.prepend( decl.clone() );
    });
});

var css    = "a { color: black; /* comment */ }";
var result = doubler.process(css);

console.log(result.css) //=>a { color: black; color: black /* comment */ }
```

`color: black /* comment */`Missing semicolon at the end, resulting in CSS syntax errors.

I hope never to omit the semicolon at the end.

`insertAfter` also have the same problem:

input:

``` css
.foo {
  display: inline-block; /* comment */
}
```

`insertAfter` output:

``` css
.foo {
  display: inline-block;
  *display: inline;
  *zoom: 1 /* comment */
}
```

Comment was not in a position behind the inline-block.
