### ISSUE TITLE
Parser failures

### ISSUE THREAD

**Issue by lahmatiy** [postcss/postcss#134]
There are some examples of correct `CSS`, but parser (tokenizer) fails for now:

``` css
:not([foo=")"]) { }
:not(div/* )/*/) { color: /**/ red }
:not(div/* ) {something} */) { }
:not(:nth-child(2n of [foo=")"])) { }
[foo=\{] { }
[foo=\(] { }
[foo=yes\:\(it\'s\ work\)] { }
```
