### ISSUE TITLE
It eats @apply overrides

### ISSUE THREAD

**Issue by fireflysemantics** [postcss/postcss#1351]
If we do this:

```css
:root {
  --toolbar-theme: {
    background-color: rebeccapurple;
    color: white;
    border: 1px solid green;
  };
}

.Toolbar {
  @apply --toolbar-theme;
   background-color: white;
}
```

`@apply` postcss will eat the override.  In other words the `background-color` will still be `rebeccapurple`.
