### ISSUE TITLE
Last semicolon on comment

### ISSUE THREAD

**Issue by ai** [postcss/postcss#136]
``` css
html {
  font-family: sans-serif; /* 1 */
  -ms-text-size-adjust: 100%; /* 2 */
  -webkit-text-size-adjust: 100%; /* 2 */
}
```

after autoprefixer, the code becomes

``` css
html {
  font-family: sans-serif; /* 1 */
  -ms-text-size-adjust: 100%; /* 2 */
  -webkit-text-size-adjust: 100% /* 2 */
}
```
