### ISSUE TITLE
problems with parsing at-rules

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss#1376]
Example of broken:
```css
@supports ({"example": 1}) {
  * { background: red; }
}

@supports (--element(".minwidth", { "minWidth": 300 })) {
  [--self] {
    background: greenyellow;
  }
}
```

Using `{`, `}` ,`(`, `)`, `{`, `}` and `func()` are allowed inside `params`

Ref: https://github.com/prettier/prettier/issues/8201
Ref: https://www.w3.org/TR/css-syntax-3/#component-value-diagram

**Comment by ai** [comment]
I think right now we have a problem only with `{}` block in params.

I think for now I will add support for nested `{}` block inside `()` because there is no use case for `@a {} {}`.

**Comment by evilebottnawi** [comment]
```css
@a {} {}
```

is invalid, here valid cases:

```css
@supports ({"example": 1}) {
  * { background: red; }
}
```
