### ISSUE TITLE
[Bug]PostCSS8 Node#insertAfter with child-node index parameter 

### ISSUE THREAD

**Issue by Genuifx** [postcss/postcss#1434]
### Description

PostCSS8 Node#insertAfter with the child-node index parameter will get the wrong output result.

Example : 

Input: 

```css
  .rule {  font-size: 15px }
```

output: 

`decl.parent.insertAfter` 

```css
  .rule { font-size: 30rpx; font-size: 15px }
```

### Reproduce Code 

```
module.exports = options => {
  return {
    Declaration(decl, index) {
        // work
        decl.parent.insertAfter(decl, decl.clone({ value: value }));
        // '.rule { font-size: 30rpx; font-size: 15px }' wrong
        decl.parent.insertAfter(index, decl.clone({ value: value }));
    }
  }
}
```
