### ISSUE TITLE
Children of @rules are parsed in the eachRules function

### ISSUE THREAD

**Issue by varemenos** [postcss/postcss#151]
So I've been trying to parse a CSS file via postcss and I've noticed (what seems to me like) a weird behavior.

postcss provides us with 2 functions, `eachRule` and `eachAtRule`:
- EachRule is a functions that was made to parse rules
- eachAtRule is made to parse `@` rules

``` css
.a{ color: red; }
@media only screen and (max-width : 768px) { .a{ color: blue; } }
```

``` js
contenter = postcss(function (css) {
  css.eachRule(function (rule) {
    console.log(rule.selector, rule.type);
  }
}

// >> a, rule
// >> a, rule
```

Why did the 2nd rule appear in there? One would expect all content (rules) of `@` rules to be only listed as children via the `eachAtRule`.

Doesn't it sound logical?
