### ISSUE TITLE
Nested css rules with postcss 8

### ISSUE THREAD

**Issue by JulienKode** [postcss/postcss#1611]
With @leozero

By upgrading postcss 7 to postcss 8 we encounter an issue.

On certain version of postcss the AST see some css with 1 selector, and with other version it is see as two selector.

The issues is available here:
https://github.com/JulienKode/postcss-8-issue
- https://github.com/JulienKode/postcss-8-issue/blob/master/dist/index.prefixed.css
- https://github.com/JulienKode/postcss-8-issue/blob/chore/working-version-postcss-8/dist/index.prefixed.css

We have two branch:
- old postcss 8 version that are working well
- new postcss 8 version that have the issue 

Here is a good example of the issue, the following css:
```css
.foo {
  svg {
    display: none;
  }

  .bar {
    display: inline;
  }
}
```

Will have this output in postcss `8.0.9`
```css 
.stuff .foo svg {
    display: none;
  }
.stuff .foo .bar {
   display: inline;
}
```

But in postcss `8.1.0` this produce this output:
```css
.stuff .foo .stuff svg {
    display: none;
  }
.stuff .foo .stuff .bar {
   display: inline;
}
```

Did you have any idea what is causing this issue and how we can resolve it ? 
For now we keep old postcss 8 version
