### ISSUE TITLE
css custom properties does not parse correctly 

### ISSUE THREAD

**Issue by barak007** [postcss/postcss#1705]
Here are few cases that postcss does not parse custom properties correctly the last one has the most potential to create bugs since the value does not contain the space and comments are easily can be removed. 
```css
/* decl.value should not contain comments (raws.value should) (minor bug since value contain the space) */
.root{--x: /*asd*/;}
/* decl.value should not contain comments (I guess it's compatible with the first issue) (minor bug since value contain the space) */
.root{--x:/*asd*/ ;}
/* this comment is parsed as comment node and the value is empty it should contain one space (major bug since the value does not contains the space) */
.root{--x:/*asd*/ }
```
