### ISSUE TITLE
postcsss 8.4.6 breaks raws

### ISSUE THREAD

**Issue by MohammadYounes** [postcss/postcss#1717]
postcss 8.4.6 contains a breaking change to `raws`. 

Test case:

```css
div { 
  font-family: "Droid Sans"/*!rtl:insert:, "Droid Arabic Kufi"*/, Tahoma;
}
```

* **v8.4.6**
![image](https://user-images.githubusercontent.com/4712046/152953113-4c03cd55-27cc-4329-ab43-2f0c514cd8a5.png)
*  **v8.4.5**
![image](https://user-images.githubusercontent.com/4712046/152952972-2812b81a-98cb-4f5a-b246-2ec9af81299c.png)
