### ISSUE TITLE
url() simple usage  SyntaxError

### ISSUE THREAD

**Issue by noyobo** [postcss/postcss#1736]
```css
.a { background-image: url(https://cdn.com/a.png) }
```

> https://developer.mozilla.org/en-US/docs/Web/CSS/url   simple usage

after postcss.process() result

```js
Result {
  processor: Processor { version: '8.4.12', plugins: [] },
  messages: [],
  root: [Getter],
  opts: {
    from: '/temp/4bc8729d.css'
  },
  css: '.a { background-image: url(https:',
  map: undefined
}
```

`//cdn.com/a.png) }`is missing
