### ISSUE TITLE
postcss-size plugin

### ISSUE THREAD

**Issue by ai** [postcss/postcss#174]
Plugin to add `size` property shorcut.

**Comment by yisibl** [comment]
Like this?

input:

```css
.foo {
  size: 30px 90px;
}
```

output:

```css
.foo {
  width: 30px;
  height: 90px;
}
```

**Comment by ai** [comment]
Yeap. Also:

```css
a {
  size: 30px;
}
```

↓

```css
a {
  width: 30px;
  height:30px;
}
```

**Comment by airen** [comment]
if the element does not have the `height`.

```
a {
   width: 30px;
}
```

Whether can be like this：

```
a {
  size: 30px * 2;
}
```
↓

```
a {
   width: 30px;
   height: 30px;
}
```

**Comment by ai** [comment]
@airen? Why we need `height` check and `* 2`? If `size` has only one value, just add both properties.

**Comment by ai** [comment]
I will made this plugin today :).

**Comment by ai** [comment]
Done https://github.com/postcss/postcss-size

**Comment by yisibl** [comment]
If there are auto values:

```css
.foo {
  size: 30px auto;
}
```

We can consider not output width or height.

```css
.foo {
  width: 30px;
}
```
