### ISSUE TITLE
How to write a plugin that runs before postcss-nested?

### ISSUE THREAD

**Issue by ZakisM** [postcss/postcss#1809]
Hi, i'm trying to write a plugin that will run before `postcss-nested`. I want the plugin to find each rule and wrap it like below:

Before:

```css
.item {
    color: red;
}

```
After:

```css
.item {
  && {
      color: red;
  }
}
```

I was able to get this working by modifying `rule.nodes[0].raws.before` and `rule.nodes[0].parent.raws.after`, however it doesn't seem to be working with `postcss-nested` as I expect. It inserts the CSS correctly, but it doesn't translate it to:

```css
.item.item.item {
    color: red;
}
```

Is it because i'm using `.raws` or could it be because the plugins aren't running in the order I expect?
