### ISSUE TITLE
Add support to scoped container queries

### ISSUE THREAD

**Issue by retroriff** [postcss/postcss#1817]
It seems that container queries are not supported, and therefore style rules are not scoped:

```css
<style lang="postcss" scoped>
.container {
  container-type: inline-size;
}

@container (min-width: rem(700)) {
  .wrapper {
    flex-direction: row;
  }
}
</style>
```

This is what we get:

```css
.wrapper[data-v-ec3ae8ce] {
    display: flex;
    flex-direction: column;
}
@container (min-width: 43.75rem)
  .wrapper {
      flex-direction: row;
      gap: 1.875rem;
  }
}
```

This makes that the container query is not rendered because the class specificity is lower.
