### ISSUE TITLE
CssSyntaxError: Unclosed bracket

### ISSUE THREAD

**Issue by merndev-agile** [postcss/postcss#1818]
Imported CSS from [react-datepicker](https://github.com/Hacker0x01/react-datepicker)  is throwing error, 
After debugging into the css of react-datepicker found out that **multiple not:() selector** are cusing the issue.If I comment that css, Project complies without any error.I am using [stylus](https://www.npmjs.com/package/stylus) and [stylelint](https://www.npmjs.com/package/stylelint) in my project. 
Below is the CSS code which is causing the issue and it  is valid syntax

```css
range:not(.react-datepicker_day--in-selecting-range,
.react-datepicker__month-text--in-selecting-range,
.react-datepicker__quarter-text--in-selecting-range,
.react-datepicker__year-text--in-selecting-range),
.react-datepicker_month--selecting-range .react-datepickermonth-text--in-range:not(.react-datepicker_day--in-selecting-range,
.react-datepicker__month-text--in-selecting-range,
.react-datepicker__quarter-text--in-selecting-range,
.react-datepicker__year-text--in-selecting-range),
.react-datepicker_month--selecting-range .react-datepickeryear-text--in-range:not(.react-datepickerday--in-selecting-range,.react-datepickermonth-text--in-selecting-range,.react-datepickerquarter-text--in-selecting-range,.react-datepicker_year-text--in-selecting-range) {
  background-color: #f0f0f0;
  color: #000;
}
```

Below is the screenshot of the error
![WhatsApp Image 2023-03-06 at 19 39 54](https://user-images.githubusercontent.com/121424822/223133425-e70c58b4-3e63-45f4-8f3e-667e7110d5b0.jpeg)

postcss version: 8.4.21
stylus version: 0.59.0
stylelint version: 15.2.0
