### ISSUE TITLE
@page for printing css syntax error

### ISSUE THREAD

**Issue by kkmuffme** [postcss/postcss#1823]
```css
@media print {
@page {
		size: landscape;
	}
}
```

Will cause postcss to fail and results in a "CssSyntaxError"

When it's formatted correctly (the @page is indented) it works correctly without error:

```
@media print {
	@page {
			size: landscape;
		}
}
```
