### ISSUE TITLE
can `tokenize.js` support single comment in module.scss ?

### ISSUE THREAD

**Issue by chaishi** [postcss/postcss#1825]
```css
// a.module.scss
@value mod from 'test.module.scss';
```

```css
// test.module.scss
.mod {
  // hello
  color: yellow;
  font-size: 30px;
}
```

`tokenize.js` can not recognise `// hello` in `test.module.scss`
