### ISSUE TITLE
postcss-transform-shortcut plugin

### ISSUE THREAD

**Issue by ai** [postcss/postcss#190]
I think we need a plugin for `transform` shortcuts like:

```css
.foo {
    rotate: 180deg;
    scale: 0.5;
}
```

↓

```css
.foo {
    transform: rotate(180deg) scale(0.5);
}
```

@MoOx there is a [W3C proposal](https://lists.w3.org/Archives/Public/www-style/2014Jul/0315.html), so it is kindly official. So it will be good in cssnext.
