### ISSUE TITLE
Plugin to find overrides

### ISSUE THREAD

**Issue by ai** [postcss/postcss#224]
Plugin can find accidental overrides:

```css
.module {
    background-repeat: no-repeat;
    background: url(lion.jpg);
    /* Oops! This will repeat. */
}
```

And raise a error.

Idea from [CSS-Tricks article](http://css-tricks.com/accidental-css-resets/).
