### ISSUE TITLE
Shorthand value expansion

### ISSUE THREAD

**Issue by dvdln** [postcss/postcss#23]
It would be great if shorthand values were expanded on parsing.

For example:

``` css
* {
  background: crimson url(omgkittens.jpg);
}
```

...could be expanded to:

``` js
{
  prop: "background",
  value: "crimson url(omgkittens.jpg)",
  expanded: {
    color: "crimson",
    image: "url(omgkittens.jpg)"
  }
}
```
