### ISSUE TITLE
postcss-messages plugin

### ISSUE THREAD

**Issue by ai** [postcss/postcss#232]
Right now many plugins print a warning messages. But build tools has a log with many unnecessary messages, so this warnings become missed.

In 4.1 we will have special API for messages #177. So, maybe we should create some plugin to add warnings directly to `body` in development mode:

```css
body:before {
    display: block;
    background: red;
    content: "Variable difinition is missed"
}
```

/cc @MoOx
