### ISSUE TITLE
Parsing error does not indicate the right line

### ISSUE THREAD

**Issue by kud** [postcss/postcss#239]
Imagine you've got:

```css
.test {
  propriety: value;
  propriety: value;
  propriety: ());
  propriety: value;
  propriety: value;
}
```

It won't indicate the line of `propriety: ());` but the line of `.test {`.

Quite disturbing.

Message:

```
originalMessage: /Users/kud/Projects/_playmedia/desktop/app/assets/mobile/styles/shared/programme-genre.css:9:3: Unclosed block
    fileName: /Users/kud/Projects/_playmedia/desktop/app/assets/mobile/styles/index.css
    lineNumber: 19
    columnNumber: 1
```
