### ISSUE TITLE
Computed values through cascading

### ISSUE THREAD

**Issue by dvdln** [postcss/postcss#24]
Would be great if PostCSS could calculate inheritance and provided computed values.

For instance:

``` css
div {
  color: lavender;
  background: linen;
}

div.shy {
  color: lavenderblush;
}
```

Could look like:

``` js
{
  selector: "div.shy",
  decls: [{
    prop: "color",
    value: "lavenderblush"
  }],
  computed: [
    <reference to own "color" decl>,
    <reference to "div { background }" decl>
  ],
  inherits: [
    <reference to "div" rule>
  ]
}
```

And yes, I understand the complexity of this. You would need to account for selector specificity, provide alternate computed decl sets based on media queries, come up with a good infrastructure for traversing the selector tree in general, etc, etc...
