### ISSUE TITLE
Parse comments in values?

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#252]
If try to extract this comment using `eachComment`, it is not recognised by the parser. Any plans to support?

```css
h1 { font-weight: /* test comment */ bold }
```
