### ISSUE TITLE
Fails to parse property values with @

### ISSUE THREAD

**Issue by 1j01** [postcss/postcss#297]
It gives a `CssSyntaxError: Unknown word`
```css
* {
  background-color: @bg-color;
  color: @fg-color;
}
```
Of course it isn't valid CSS now, but it will be, I promise!
I thought by switching from rework to postcss I'd be able to get rid of an ugly regexp hack to handle @define-color declarations, and I did, but it looks like I'll have to replace it with a (somewhat less ugly) regexp hack to handle variable references :neutral_face:
