### ISSUE TITLE
Empty "before" value when input file is UTF-8 encoded.

### ISSUE THREAD

**Issue by MohammadYounes** [postcss/postcss#32]
##### Input

``` CSS
/*******************************
  Sample Content
*******************************/

/*comment before first rule*/
.sample {
  margin:10px;
}
```
##### Output

``` javascript
{ type: 'rule',
  decls:
   [ { type: 'decl',
       parent: [Circular],
       source: [Object],
       before: '\r\n  ',
       prop: 'margin',
       between: '',
       _value: [Object] } ],
  parent:
   { type: 'root',
     rules: [ [Circular] ],
     after: '',
     lastEach: 1,
     indexes: { '1': 0 } },
  source: { start: { line: 1, column: 1 }, end: { line: 8, column: 1 } },
  before: '',
  _selector:
   { raw: '?/*******************************\r\n  Sample Content\r\n************
*******************/\r\n\r\n/*comment before first rule*/\r\n.sample ',
     trimmed: '.sample' },
  semicolon: true,
  after: '\r\n' }
```
