### ISSUE TITLE
preserve whitespace between selectors

### ISSUE THREAD

**Issue by cvrebert** [postcss/postcss#37]
If I do something like this:

``` js
postcss(function (css) {
    css.eachRule(function (rule) {
        rule.selectors = rule.selectors.map(function (selector) {
            // In reality, I would modify the selector, but for simplicity, I won't in this example.
            return selector;
        });
    });
});
```

And run it on a CSS file like:

``` css
.foo,
.bar,
.baz {
    float: left;
}
```

Then the output will end up changing the whitespace between selectors to spaces:

``` css
.foo, .bar, .baz {
    float: left;
}
```

Is (or will) there be a way to preserve the original whitespace-between-selectors code style convention, or to at least set what convention postcss imposes here? Or am I doomed to splitting/parsing the selectors string myself if I want to control this?
