### ISSUE TITLE
Detect/remove browser hacks based on browserslist?

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#378]
One of the things that I didn't do yet in cssnano is to remove old browser properties. csswring does this somewhat, but it only cleans `decl.before` and so the property remains in the CSS, except now it is a "real" property:

```css
h1 {
  color: blue;
  *color: red;
}
```

Becomes:

```css
h1 {
  color: blue;
  color: red; /* undesirable! */
}
```

Now it is red in all browsers. The desired output would be something like this:

```css
h1 {
  color: blue;
}
```

Such a module would use browserslist, like autoprefixer, to allow a consumer to set a range of browsers that they want to support. Then, it could be used for my use case to remove hacks, but also I think it would be really great if it could be used in stylelint, to warn developers not to use certain tricks.

There's a nice list over at http://browserhacks.com/ that we could use. Would appreciate it if anyone had some input on the idea. :smile:
