### ISSUE TITLE
PostCSS should support optional charset parameter in inline sourcemaps

### ISSUE THREAD

**Issue by Panya** [postcss/postcss#383]
According to [RFC2397](https://tools.ietf.org/html/rfc2397) `data:uri` scheme may include optional charset parameter for text mime types.

Suppose, we have a generated file with unicode symbols and inlined sourcemap with a specified charset (we want to view it in Chrome DevTools). For example: 
```css
.test {
  content: 'привет';
}
/*# sourceMappingURL=data:application/json;charset=utf-8;base64,...*/
```
Right now if we try to use PostCSS with this file it fails with error:
```
Error: Unsupported source map encoding charset=utf-8;base64
```

I think PostCSS should consider optional charset (at least `utf-8`) and correctly apply previous sourcemap in this case.
