### ISSUE TITLE
Type module

### ISSUE THREAD

**Issue by daleeidd** [postcss/postcss#410]
It would be great if there was a `Type` module which can determine the type of values and other things.

It could be as simple as:
```js
postcss.type('1rem');                // 'length'
postcss.type('red');                 // 'color'
postcss.type('.something');          // 'class'
postcss.type('#id');                 // 'id'
postcss.type('calc(10rem * 10rem)'); // 'function'
postcss.type('@media {}');           // 'atrule'

postcss.type('1rem') === 'length'; // true
```

The above may not be too vague – even though those are the correct CSS types. It can be even more informative by giving more type information:
```js
postcss.type('1rem');                // ['length', 'rem']
postcss.type('red');                 // ['color', 'keyword']
postcss.type('.something');          // ['selector', 'class']
postcss.type('#id');                 // ['selector', 'id']
postcss.type('calc(10rem * 10rem)'); // ['function', 'calc']
postcss.type('@media {}');           // ['atrule', 'media']

postcss.type('1rem').includes('length'); // true
```

Finally, another option is to return rich type information:
```js
postcss.type('1rem');                // { types: ['value', 'length'], name: 'rem' }
postcss.type('red');                 // { types: ['value', 'color'], name: 'red' }
postcss.type('.something');          // { types: ['selector', 'class'], name: 'something' }
postcss.type('#something');          // { types: ['selector', 'id'], name: 'something' }
postcss.type('calc(10rem * 10rem)'); // { types: ['value', 'function'], name: 'calc' }
postcss.type('@media {}');           // { types: ['atrule'], name: 'media' }

postcss.type('1rem').types.includes('length'); // true
```

The `atrule` may seem unnecessary, but it could prove to be useful in the form of convenience.

**Comment by ai** [comment]
Can you describe your user case for this library? Maybe we can find better API.

**Comment by daleeidd** [comment]
For the plugin I wrote: [postcss-define-property](https://github.com/daleeidd/postcss-define-property)

With type information, it could allow the definition of custom property shorthands similar to native ones by adding type information to the signature.

```css
/* Input */
border: $width<border-width> $radius<length, percentage> $style<border-style> $color<color> {
  border: $width $style $color;
  border-radius: $radius;
}

border: $width<border-width> $radius<length, percentage> {
  border-width: $width;
  border-radius: $radius;
}

border: $width<border-width> $color<color> {
  border-width: $width;
  border-color: $color;
}

.something {
  border: 25px 10px;
}

.nothing {
  border: 25px blue;
}
```
```css
/* Output */
.something {
  border-width: 25px;
  border-radius: 10px;
}

.nothing {
  border-width: 25px;
  border-color: blue;
}
```
If the syntax looks bad, it is because I just made it up on the spot (WIP). Without some way to parse the types for values, those signatures wouldn't be possible.

As an option, I could find or write an external library for which PostCSS can depend on.

**Comment by ai** [comment]
Why you need types here? [postcss-mixins](https://github.com/postcss/postcss-mixins) hase same semantic without types.

**Comment by ben-eb** [comment]
This has come up in the Gitter chat before. @jonathantneal started work on something similar.

I agree that this would be beneficial. One of the things I want to work on is normalizing `border` values; these are all equivalent:

```css
h1 {
  border: 1px solid red;
  border: 1px red solid
  border: solid red 1px;
  border: solid 1px red;
  border: red 1px solid;
  border: red solid 1px;
}
```

Knowing which values are units, which are colours & which are keywords would be really great for this use case and others.
