### ISSUE TITLE
Incorrect (?) behavior when input starts with AtRule

### ISSUE THREAD

**Issue by tanraya** [postcss/postcss#42]
I have following css:

``` css
@import url(http://fonts.googleapis.com/css?family=Oswald);

html, body {
  padding: 0;
  margin: 0;
}
```

When PostCSS parses css, it suggests that all following nodes are `AtRule` children:

```
{ type: 'atrule',
  parent: 
   { type: 'root',
     rules: 
      [ [Circular],
        [Object]
```

Is this correct behavior? I think this is a bug, PostCSS should not do this when we using `@import` rule.
