### ISSUE TITLE
Autoreset plugin

### ISSUE THREAD

**Issue by ai** [postcss/postcss#470]
In BEM we can find a elements rules. Lets add reset stylus to each element rule.

```css
.block_elem {
  color: black;
}
.block_elem.__mod {
  color: white;
}
```

```css
.block_elem {
  padding: 0;
  /* other reset decls */
  color: black;
}
.block_elem.__mod {
  color: white;
}
```

Plugin can accepts `shouldBeReset` callback for custom methodologies:

```js
shouldBeReset: (rule) => !rule.selector.match(/__/)
```
