### ISSUE TITLE
Write SVG in PostCSS

### ISSUE THREAD

**Issue by ai** [postcss/postcss#553]
@ben-eb suggested great idea to write SVG inside CSS with some plugin like `postcss-write-svg`:

```css
.arrow {
    @svg {
        polygon {
            fill: green;
            points: 50,100 0,0 0,100; 
        }
    }
}
```

to:

```css
.arrow {
  background: url(data:…);
}
```

Of course big SVG like icons should be draw in vector editor. But small cases like “HTML art” for arrows and simple poligons can be done in CSS by hands.
