### ISSUE TITLE
Wrong formatting

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss#56]
There's a difference between 0.3.4 and 1.0.0 with formatting:

For example, this code:

``` css
:root {
    --width    :50px;
}

body {
    display: flex;
    order: 2;
}
```

Postcss0.3.4:

``` css
:root {
    --width    :50px;
}

body {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-ordinal-group: 3;
    -webkit-order: 2;
        -ms-flex-order: 2;
            order: 2;
}
```

Postcss1.0.0:

``` css
:root {
    --width    :50px;
}

body {
    display    :-webkit-box;
    display    :-webkit-flex;
    display    :-ms-flexbox;
    display: flex;
    -webkit-box-ordinal-group    :3;
    -webkit-order    :2;
        -ms-flex-order    :2;
            order: 2;
}
```

The first "pattern" found is kept all the time.
