### ISSUE TITLE
Javascript enhanced transforms.

### ISSUE THREAD

**Issue by DylanPiercey** [postcss/postcss#577]
I understand that postcss and is purely preprocessing css at the moment. I think that this is extremely limiting, specifically for things like css polyfills. What I am about to propose may be out of scope for this project but I just want to get people thinking about polyfilling the more tricky features of css4/beyond.

I'm thinking of stuff like this:

```css
/* Input */
.myclass {
    position: sticky;
    top: 10px;
    color: green;
}

/* Output */
.__sticky {
    /* Generic sticky styles if needed */
    position: fixed;
}

.myclass {
    color: green;
}
.__sticky.myclass {
/* Selector specific styles */
    top: 10px;
}
```

In this case the generated javascript would look something like this:

```javascript
// We could output our lists of selectors and some config that require js and generate a javascript polyfill during css compilation.

const POST_CSS = {
   "sticky": [
       {
             selector: ".myClass",
             options: {
                  top: 10px;
             }
       }
    ]
}; 

// And then we could have custom javascript handlers for any transform that needs it.
window.addEventListener("scroll", function () {
    POST_CSS.sticky.forEach(function (rule) {
        let matches = document.querySelectorAll(rule.selector);
        for (let el of matches) {
            if (window.pageYOffset > el.offsetTop + rule.options.top) {
                el.addClass(".__sticky");
            } else {
                el.removeClass(".__sticky");
            }
        }
    });
});
```

The idea here is that we can use postcss to generate both css and some related javascript. Now this example wouldn't be terribly efficient (although it could be much better). However I think that this is something that the css community as a whole should start exploring.

There are some libraries out there that attempt to manually parse the css at runtime and provide transforms but this is costly. I think there could be mostly performant polyfills for pretty much any new or custom css feature if we were to start leveraging both preprocessing and javascript.

What do you guys think?

---

This was also posted [here](https://github.com/cssnext/cssnext/issues/221)
