### ISSUE TITLE
decl. node raws.between boundaries

### ISSUE THREAD

**Issue by MohammadYounes** [postcss/postcss#598]
If a declaration value starts with a comment, that comment will be considered as part of `node.raws.between` rather than being part of  `node.raws.value`

For example:

``` css
   body{
        font-family: /*before*/ Tahoma /*after*/;
    }
```

Produces:

``` js
{ raws:
   { before: '\r\n        ',
     between: ': /*before*/ ',
     value: { value: 'Tahoma ', raw: 'Tahoma /*after*/' }
   }
}
```

While I expected:

``` js
{ raws:
   { before: '\r\n        ',
     between: ': ',
     value: { value: 'Tahoma ', raw: '/*before*/ Tahoma /*after*/' }
   }
}
```

Shouldn't the comment be part of the value ? 

Thanks.
