### ISSUE TITLE
postcss-clone

### ISSUE THREAD

**Issue by ai** [postcss/postcss#655]
@ngduc suggested idea, that we need plugin to clone some class to other.

It will be very useful to extend CSS libraries like Bootstrap:

```css
.myBtn {
    @clone .btn-default;
    color: red
}
```

Same thing in Less can be done by:

```less
.myBtn {
    .btn-default;
    color: red
}
```

@ben-eb suggested that `postcss-reference` does very clloe thing. But I think we need better, more clone API.
