### ISSUE TITLE
`raws.before` and weird property name

### ISSUE THREAD

**Issue by hail2u** [postcss/postcss#661]
Current [API Doc][1] says:

> - `before`: the space symbols before the node. It also stores any non-standard symbols before the declaration, like `_` from an IE hack.

But PostCSS parses following CSS:

```css
.foo {
  <color: red;
}
```

Into:

```javascript
Declaration {
  raws: { before: '\n  ', between: ': ' },
  type: 'decl',
  prop: '<color',
  value: 'red' }
```

If API docs correct, the `<` character should be included in `raws.before` not in `prop` because `<` is *non-standard symbol*.

Is it documentation bug or PostCSS parser bug?

[1]: https://github.com/postcss/postcss/blob/f9406dcfba9979b2d3b7fa8af7a1bff40af7f11a/docs/api.md#noderaws

**Comment by ai** [comment]
`before` stores only common symbols, that are used for IE hack. `<` is not used as a hack, so I didn’t copy it to `before`.

https://github.com/postcss/postcss/blob/master/lib/parser.es6#L212-L215

**Comment by ai** [comment]
I fix a docs 6c7e652

**Comment by ai** [comment]
@hail2u BTW, please check your email Inbox. I need your post address to send you a New Year postcard and sticker :).

**Comment by ben-eb** [comment]
@ai *Actually*, all these work in IE7 or less:

```css
.selector { !property: value; }
.selector { $property: value; }
.selector { &property: value; }
.selector { *property: value; }
.selector { )property: value; }
.selector { =property: value; }
.selector { %property: value; }
.selector { +property: value; }
.selector { @property: value; }
.selector { ,property: value; }
.selector { .property: value; }
.selector { /property: value; }
.selector { `property: value; }
.selector { ]property: value; }
.selector { #property: value; }
.selector { ~property: value; }
.selector { ?property: value; }
.selector { :property: value; }
.selector { |property: value; }
```

via http://browserhacks.com/
