### ISSUE TITLE
Question: what is the expected result for the functions append() and prepend()?

### ISSUE THREAD

**Issue by 7studio** [postcss/postcss#67]
Hi Andrey,
I have a weird output behavior with the function `append()`. Maybe you can help me to resolve it.

I have this following sources:
**`a.css`**:

``` css
h1 { color: blue; }
```

**`b.css`**:

``` css
body { background-color: green; }
```

and this following code:

``` js
var cssA = fs.readFileSync("a.css", "utf-8");
var cssB = fs.readFileSync("b.css", "utf-8");

var fileA = postcss.parse(cssA);
var fileB = postcss.parse(cssB);

fileA.append(fileB);

var result = fileA.toResult();

fs.writeFileSync('append.out.css', result.css);
```

with this result in **`append.out.css`**:

``` css
h1 { color: blue; }body { background-color: green; }
```

Should the two rules not be separated by a line-break ? If your answer is **not**, can you explain me why the function `prepend()` does ;)
**`prepend.out.css`**:

``` css
body { background-color: green; }
h1 { color: blue; }
```

I took time to do more tests and the code below outputs one more different result:

``` js
var fileA = postcss.parse("h1 { color: blue; }");
var fileB = postcss.parse("body { background-color: green; }");

fileA.append(fileB);

var result = fileA.toResult();

result.css //=> 'h1 { color: blue; }body { background-color: green; }'
```

I appreciate your time and attention.
