### ISSUE TITLE
Generator to build plugins with components library

### ISSUE THREAD

**Issue by ai** [postcss/postcss#693]
We need a generator to build Bootstrap like libraries with components with syntax like:

```css

@my-lib-globals {
    color: blue;
}

.my-project-button {
    @my-lib button {
        color: red;
    }
}
```

**Comment by stephenway** [comment]
Curious, would you be able to use these components like mixins by specifying arguments?

```css
.button-with-args {
  @bootstrap button primary;
}

/* or */

.button-no-args {
  @bootstrap button-primary;
}
```

**Comment by ai** [comment]
@stephenway good question :). I think second one is easy. But let’s geneator author will decide :).

**Comment by stephenway** [comment]
@ai Thanks for the response. I'm in the middle of writing a large set of components using mixins, and if this is flexible I might consider adopting this code pattern.

**Comment by fernandofleury** [comment]
I would like to help on it.

**Comment by moshemo** [comment]
I have been trying to create something similar using semantic-ui (personally speaking, I like semantic-ui more than bootstrap).  

My vision is to have the basic CSS feel like native CSS with atrules for variables.  For instance:  

For instance:

    @primary-color: #fdecba;

    button {
        button: button;
        button-color:  #abcdef;
        button-background-color: @primary-color;
        }
 
    button.disabled {
        button: disabled;
     }

I am working on a button version right now and then hope to work on a menu version.

**Comment by ai** [comment]
@moshemo your syntax has few problems:

1. `@primary-color` — other developers will not know the source of this variable. What plugin it configure?
2. Same problem with `button:` property. If new developer will see this property in project, she/he will go to MDN and will not find `button` property in CSS spec. Or what you will do, if W3C will add `button` property in future?

This is why I create this issue. We need better syntax for components library.

Look at suggested syntax:

```css
@bootstrap-globals {
    color: blue;
}

.my-project-button {
    @bootstrap button {
        color: red;
    }
}
```

Every our at-rule has `bootstrap` prefix. So you will understand, that it is not a standard CSS, but it comes from something like `postcss-bootstrap`.
