### ISSUE TITLE
Postcss split custom values

### ISSUE THREAD

**Issue by LestaD** [postcss/postcss#723]
I create plugin `postcss-define-units`.
But with webpack, postcss add space between value and custom unit:

i wrote:
```css
.class {
  --define: dp 2px;
  width: 2dp;
}
```

Output without plugins only in webpack:

```css
.class {
  --define: dp 2px;
  width: 2 dp;
}
```
