### ISSUE TITLE
Function Resolution

### ISSUE THREAD

**Issue by thejameskyle** [postcss/postcss#736]
I wanted to open a discussion about how to solve the problem of nesting CSS "functions" with PostCSS when the order of PostCSS plugins is significant. aka

```css
element {
  /* can't resolve because the order of plugin1 and plugin2 is significant in PostCSS plugins */
  property: plugin1(plugin2(plugin1(value)));
}
```

I created a repo to demonstrate the issue and suggest a solution:

https://github.com/thejameskyle/postcss-function-resolution
