### ISSUE TITLE
Allow to parse at-rule inside declarations

### ISSUE THREAD

**Issue by ai** [postcss/postcss#75]
`@page` can also contains other at-rules, like:

``` css
@page {
    margin-top: 10px;
    @bottom-center { ... /* page number */}
}
```
