### ISSUE TITLE
Add one source mapping for each selector in a rule

### ISSUE THREAD

**Issue by lydell** [postcss/postcss#76]
Minifiers and tools such as [rework-inherit](https://github.com/reworkcss/rework-inherit/) (imagine a similar one for postcss) can combine selectors from several different places into a single rule in the output. Currently, only one single source mapping is added for all selectors of a rule, but in this case we’d need one for each selector.

Take the rework-inherit example:

``` css
.gray {
  color: gray;
}

.text[href {
  inherit: .gray;
}
```

Yields:

``` css
.gray,
.text[href {
  color: gray;
}
```

Note the missing `]` in `.text[href`. The browser would then say that there’s a syntax error on line 1, column 1, when the error actually is on line 5, column 1.
