### ISSUE TITLE
Add PostCSS to Pretty Diff beautifier

### ISSUE THREAD

**Issue by prettydiff** [postcss/postcss#770]
I would like to add Post CSS support to the Pretty Diff beautifier.  Is there a collection of unique Post CSS code samples or unit tests that I could run through Pretty Diff to identify current gaps in support?

**Comment by ai** [comment]
PostCSS is just a CSS parser :). There difference with standard CSS parse is that PostCSS parser ignore many issues.

1. Property names can contain any symbols. For example, it can start from `$`.
2. Parser do not check a context. So properties can be in the root. Or rules can be inside another rule.

So, main difference example will be:

```scss
$one: 1;

a {
  b {
    $two: 2;
    @any-name-that-we-want {
      em { }
    }
  }
}
```
