### ISSUE TITLE
Parsing issue with <![CDATA[ inside a CSS comment

### ISSUE THREAD

**Issue by eramdam** [postcss/postcss#816]
I stumbled upon a string that PostCSS seems to parsing incorrectly

```css
/*<![CDATA[*/
        /* everything in this node will be inlined */
        /* ==== Page Styles ==== */

        body,
        #backgroundTable {
            background-color: #f2f2f2;
            /* Use body to determine background color */
            font-family: sans-serif;
        }
```

PostCSS seems to think that `<![CDATA[ body` is a selector even though `<![CDATA[` is inside a comment, resulting in issues when passing `<![CDATA[ body` to `postcss-selector-parser`
