### ISSUE TITLE
result.warn discards // when calculating error index

### ISSUE THREAD

**Issue by dryoma** [postcss/postcss#859]
Trying to parse comments in styles (to work around PostCSS ignoring some inline //-comments) in a stylelint plugin. The SCSS (parsed with `postcss-scss` syntax):

```scss
//
// 1. Address appearance set to searchfield in Safari and Chrome.
// 2. Address box-sizing set to border-box in Safari and Chrome.
//

input[type="search"] {
  -webkit-appearance: textfield; // 1
  box-sizing: content-box; //2
}
```
The comment `//2` start index is 227 (0-based). So the column of the warning should be 28 in this example. No Node object is instantiated, so `result.warn` (actually, stylelint's `report`, but the result is the same) gets `root` as `node`.

```js
result.warn(message, {
  severity,
  rule: ruleName,
  node: root,
  index
})
```
returns a warning with the column number of 18. By playing with the SCSS code I found out that all `//` when in SCSS comments are ignored.

Is it by design, a bug or am I missing something?

----
(the examples above are just samples, while the in the wild: the [comment parsing util](https://github.com/kristerkari/stylelint-scss/blob/comment-fix/src/utils/findCommentsInRaws.js), warning is produced [here](https://github.com/kristerkari/stylelint-scss/blob/comment-fix/src/rules/double-slash-comment-whitespace-inside/index.js#L46), the failing test case: [this](https://github.com/kristerkari/stylelint-scss/blob/comment-fix/src/rules/double-slash-comment-whitespace-inside/__tests__/index.js#L47) and [the following](https://github.com/kristerkari/stylelint-scss/blob/comment-fix/src/rules/double-slash-comment-whitespace-inside/__tests__/index.js#L63))
