### ISSUE TITLE
Blank lines are stripped from css.toString()

### ISSUE THREAD

**Issue by andywer** [postcss/postcss#887]
Compare postcss/postcss-import#206

**Comment by ai** [comment]
Could you add code examples?

**Comment by andywer** [comment]
Sure. My particular problem in `postcss-debug` is this:

```js
postcss.plugin('postcss-debug-snapshot', () => (
  css => {
    console.log(css.toString())    // blank lines are gone
  }
))
```

**Comment by ai** [comment]
What is `css` in your example above? ;) Please show me in what cases PostCSS ignore blank lines ;)

**Comment by andywer** [comment]
`css` (first parameter of the `pluginFunction`), is a [Root](http://api.postcss.org/Root.html).

My sample CSS that confirmed the problem one of my plugin's users described was:
```css
.test {
  color: black;

  &:hover {
    margin-top: calc(10px + 20px);
  }
}
```

The blank line between `color: black;` and `&:hover {` is gone on `css.toString()`.

Hope that helps :)

**Comment by ai** [comment]
I you sure? Here is my test:

```js
let postcss = require('./');

let css = '.test {\n' +
'  color: black;\n' +
'\n' +
'  &:hover {\n' +
'    margin-top: calc(10px + 20px);\n' +
'  }\n' +
'}\n';

console.log(postcss.parse(css).toString())
```

And result is correct:

```css
.test {
  color: black;

  &:hover {
    margin-top: calc(10px + 20px);
  }
}
```

Do you know, that when you clone some node, PostCSS will remove all whitespace symbols? Maybe this is why blank line is missed.
