### ISSUE TITLE
Babel for CSS

### ISSUE THREAD

**Issue by artemgurzhii** [postcss/postcss#898]
Have you thought about making a PostCSS pugin for CSS like Babel for JS? I think it will be a big step in front-end world. Here is example of what I mean.

```css
.ul li:not(:last-of-type) {
 bacground-color: black;
}
```
would compiled to
```css
.ul li {
 bacground-color: black;
}
.ul li:last-of-type {
 background-color: transparent;
}
```
