### ISSUE TITLE
Missing semicolon if order of nodes is changed

### ISSUE THREAD

**Issue by hudochenkov** [postcss/postcss#918]
I'm changing order of rule nodes. Just simple `.reverse()`: http://astexplorer.net/#/2uBU1BLuJ1/7

Input:

```scss
a {
	@extend .something;
	@mixin hiya {
		display: none;
	}
}

a {
	@mixin hiya {
		display: none;
	}
  	@extend .something;
}
```

Output:

```scss
a {
	@mixin hiya {
		display: none;
	}
	@extend .something
}

a {
  	@extend .something;
	@mixin hiya {
		display: none;
	}
}
```

In the first rule semicolon after `@extend` is missing. I suppose it happens because of `.raws.semicolor: false` on the rule.

If it's an intended behaviour, can you, please, suggest some workaround to preserve semicolon for each node?

**Comment by ai** [comment]
Main problem that in this case PostCSS could not detect does user want to write semicolon.

```css
a {
	@extend .something;
	@mixin hiya {
		display: none;
	}
}
```

You could detect by some logic in your plugin and then force all `raws.semicolon` to same value if last child is `Rule`.

Problem that semicolon logic was created for standard CSS. I am open for any parse changes, but I need some strict rules.
