### ISSUE TITLE
Stricter string parsing

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#923]
According to the specification, newlines (`\n`) are invalid in CSS strings unless escaped with a backslash. So, this example is invalid:

```css
h1:after {
  content: "


  ";
}
```

But this is valid:

```css
h1:after {
  content: "\
\
\
  ";
}
```

Ref: https://www.w3.org/TR/CSS2/syndata.html#strings
