### ISSUE TITLE
Decls without ;

### ISSUE THREAD

**Issue by ai** [postcss/postcss#93]
Current PostCSS parses

``` css
a {
  color: white
  width: 1px
}
```

As one declaration with `color` name and `white\n  width: 1px` value.

We need to fix it:
- In normal mode PostCSS should print error.
- In safe mode PostCSS should parses it as 2 decls.
