### ISSUE TITLE
Confusing `raws` behaviour

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#933]
Ref: [December 23, 2016 10:11 AM](https://gitter.im/ben-eb/cssnano?at=585cf868c02c1a3959a3638d)

```css
    --layout-around-aligned: {
      -ms-flex-line-pack: distribute;  /* IE10 */
      -ms-align-content: space-around;
      -webkit-align-content: space-around;
      align-content: space-around;
    };

    /*******************************
              Other Layout
    *******************************/

    --layout-block: {
      display: block;
    };
```

I looked into the AST produced by PostCSS and what ends up happening is that the semicolon from (logically) the first rule is in fact tacked on to the `before` raw value of the comment node. Because cssnano removes the comment nodes then the semicolon is lost, but I don't think that the semicolon being part of the comment node is correct.

**Comment by ai** [comment]
Is it correct CSS? I thought that `;` could not be in rules context

**Comment by ben-eb** [comment]
Yeah, it's correct, there's a nice blog post on CSS mixins here https://blog.hospodarets.com/css_apply_rule. 😄 

e.g.

```css
:root {
  --zero-size: {
    width: 0;
    height: 0;
  };
  
  --triangle-to-bottom-size: 50px;
  --triangle-to-bottom-color: #007bff;
  
  --triangle-to-bottom: {
    @apply --zero-size;
    border-style: solid;
    border-width: var(--triangle-to-bottom-size) var(--triangle-to-bottom-size) 0 var(--triangle-to-bottom-size);
    border-color: var(--triangle-to-bottom-color) transparent transparent transparent;
  };
}

.triangle-to-bottom {
  @apply --triangle-to-bottom;
}
```
