### ISSUE TITLE
PostCSS is erroring on aspect ratio media query

### ISSUE THREAD

**Issue by Dan503** [postcss/postcss#945]
I have downloaded the latest version of postCSS just to be sure it wasn't a version issue. 

When I use this css, I get a "Cannot read property '1' of null" error

`````css
@media screen and (max-aspect-ratio: 2/1){
	* {
		background: red;
	}
}
`````

I am using gulp-postcss to run postCSS and the error still occurs even when I remove all postcss plugins.

The error doesn't seem to be impacting postCSS's ability to do it's job though. My postCSS plugins all still seem to be functioning correctly even when the error is being logged.

The postCSS plugins I have installed are autoprefixer and px2rem.
