### ISSUE TITLE
Semicolon Stripped

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss#969]
[First opened issue here](https://github.com/postcss/postcss-custom-properties/issues/62)

**Comment by ben-eb** [comment]
Probably related: https://github.com/postcss/postcss/issues/364

**Comment by ai** [comment]
@oleersoy I need input, output and expected output.

**Comment by oleersoy** [comment]
@ai did you look at the link I posted?

**Comment by ai** [comment]
Sorry, I am front long flight and will slow internet. Could you help me and show input, output and expected output in this test?

**Comment by oleersoy** [comment]
Sure.  This is the file [content being built](https://github.com/superfly-css/superfly-css-utilities-colors/blob/master/src/main/css/index.css)

``` css

/*! superfly-css-utilities-colors | MIT License | https://github.com/superfly-css/superfly-css-utilities-colors/blob/master/LICENSE.md */

/* =======================================
   COLORS
   0: Import shared color variables
   1: Gray background color utilities
   2: Notification background color utilities
   --------------------------------------
   -- Naming Conventions --
   --------------------------------------
   All background color classes start with
   `u-color-background-`.
   --------------------------------------
   ======================================= */
/* 0 */
@import "superfly-css-variables-colors";

/* 1 */
@each $weight in 100, 300, 400, 500, 600, 700, 900 {
    .u-color-background-gray-$(weight) {
      background-color: var(--color-gray-$(weight)) !important;
    }
}

/* 2 */
@each $weight in 100, 300, 500, 700, 900 {
  @each $brand in primary, success, info, warning, danger {
    .u-color-background-$(brand)-$(weight) {
      background-color: var(--color-$(brand)-$(weight)) !important;
    }
  }
}
```

When the build finishes it places the resulting file in `target/src/main/resources`, however the `;` is stripped off the `!important;` part of the input.

**Comment by ai** [comment]
PostCSS right now do not guarantee that output format will be equal to input. It could loose some things. We are planing to fix it in 6.0.

Is it critical for you? If it is critical, you can add custom plugin to restore your code style.

**Comment by oleersoy** [comment]
Here's a few samples of the actual output:
``` css
.u-color-background-gray-100 {

    background-color: rgb(232, 232, 232) !important
}

.u-color-background-gray-300 {

    background-color: rgb(199, 199, 199) !important
}

.u-color-background-gray-400 {

    background-color: rgb(166, 166, 166) !important
}
```
