### ISSUE TITLE
add line breaks to the comment node

### ISSUE THREAD

**Issue by sullenor** [postcss/postcss#981]
Hello,

I work on a small plugin, which merges files together and would like to add some annotations to the resulting file. Currently, I use the postcss helper [comment](http://api.postcss.org/postcss.html#.comment):

```css
const {comment, plugin, root} = require('postcss');
// ...

const myPlugin = plugin('myPlugin', () => {
  return (ast, result) => {
    const rootTree = root();
    // ...

    rootTree.append(comment({text: 'the comment of mine'}));
    rootTree.append(ast.nodes);
    result.root = rootTree;
  };
});
```

and would like to know how to add additional line breaks to the comment node?
